services:
  # Development overrides for API
  api:
    volumes:
      - .:/app
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

  # Development overrides for Domain Worker
  celery_domain_worker:
    volumes:
      - .:/app

  # Development overrides for Scan Worker
  celery_scan_worker:
    volumes:
      - .:/app

  celery_beat:
    env_file: .env.dev
    volumes:
      - .:/app