services:
  api:
    env_file: .env.dev
    volumes:
      - .:/app
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

  celery_domain_worker:
    env_file: .env.dev
    volumes:
      - .:/app

  celery_scan_worker:
    env_file: .env.dev
    volumes:
      - .:/app

  celery_beat:
    env_file: .env.dev
    volumes:
      - .:/app